### ISSUE TITLE
Application is crash without select the day

### ISSUE THREAD

**Issue by ram2386** [vyasanirudh/AVCalendar#1]
Steps to reproduce.
1. Select the 31st day in October month.
2. Change the month from October to September then focus is gone of the selected day.
3. Click on the check icon below and notice that the application is crash.

File Name: APCustomCalendarContainer.swift
Structure Name: internal struct _AVDate {}
Message: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by vyasanirudh** [comment]
@ram2386 Thanks for the feedback. Will surely correct and update in sometime.

**Comment by vyasanirudh** [comment]
Handled. Haptic feedback added when no date is selected. Will make further improvements in the further releases.
